version: '3.5'
services:
  redis:
    image: redis:alpine
    container_name: redis
    # command: redis-server --requirepass redis123
    command: redis-server 
    restart: on-failure
    volumes:
      - ./data:/var/lib/redis
      # - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT:-6379}:6379
    environment:
      - REDIS_REPLICATION_MODE=master 
    networks:
      - services

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      # REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - 8020:8081
    networks:
      - services

  # nf-explorer:
  #   image: gesellix/nf-data-explorer
  #   hostname: nf-explorer
  #   container_name: nf-explorer
  #   depends_on:
  #     - redis
  #   ports:
  #     - '8020:80'
  #   command: yarn start
  #   networks:
  #     - services
  #   environment:
  #     - CASSANDRA_HOST=cassandra
  #     - REDIS_HOST=redis
  #   volumes:
  #     - ./data:/apps/nf-data-explorer/data

networks: 
  services:
    name: ${APP_NAME:-irbigdata}_network
